// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/products": {
    params: {};
  };
  "/products/:id/details": {
    params: {
      "id": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/products" | "/products/:id/details";
  };
  "pages/index.tsx": {
    id: "pages/index";
    page: "/";
  };
  "pages/products/index.tsx": {
    id: "pages/products/index";
    page: "/products";
  };
  "pages/products/detail.tsx": {
    id: "pages/products/detail";
    page: "/products/:id/details";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "pages/index": typeof import("./app/pages/index.tsx");
  "pages/products/index": typeof import("./app/pages/products/index.tsx");
  "pages/products/detail": typeof import("./app/pages/products/detail.tsx");
};